version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://nest:secret@db:5432/app
      FUSE_API_KEY: heregoesthevalidapi-key
      FUSE_API_URL: https://api.challenge.fusefinance.com
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "dist/src/main.js"]

volumes:
  pgdata:
